'use strict'

/**
 * Doc Auto-Updater — reads a stale doc + changed source files, uses LLM to generate
 * an incremental update, bumps version, writes back.
 */

const fs = require('fs')
const path = require('path')
const { callLLM } = require('./llm.js')
const { bumpPatch, VERSION_RE, recordUpdate } = require('./doc-manifest.js')

const UPDATE_PROMPT = `You are updating a technical documentation file. Some source files it references have changed.

CURRENT DOC:
{{current_doc}}

CHANGED SOURCE FILES (new content):
{{changed_sources}}

INSTRUCTIONS:
- Update ONLY the sections affected by the source file changes
- Keep all other content exactly as-is
- Update version number: {{old_version}} → {{new_version}}
- Update the "Last updated" date to {{today}}
- Preserve the exact markdown formatting, headers, tables
- Do NOT add commentary or explanation — return only the updated document
- If changes are minimal (e.g. a variable renamed), make minimal edits
- If a new function/feature was added, add a new section or table row

Return the COMPLETE updated document (not just the diff).`

/**
 * Update a single stale doc.
 * @param {string} projectRoot - Project root dir
 * @param {string} stateDir - ~/.quoth/intelligence/
 * @param {Object} staleInfo - { doc, version, changedFiles }
 * @param {Function} log - Logging function
 * @returns {Object|null} { doc, oldVersion, newVersion } or null on failure
 */
async function updateDoc(projectRoot, stateDir, staleInfo, log) {
  const docsDir = path.join(projectRoot, 'docs', 'project')
  const docPath = path.join(docsDir, staleInfo.doc)

  let currentDoc
  try { currentDoc = fs.readFileSync(docPath, 'utf8') } catch { return null }

  // Read changed source files
  const changedSources = []
  for (const src of staleInfo.changedFiles.slice(0, 5)) { // Max 5 files to keep prompt size reasonable
    const candidates = [
      path.join(projectRoot, src),
      path.join(projectRoot, 'quoth-plugin', src),
      path.join(projectRoot, src.replace(/^quoth-plugin\//, '')),
    ]
    for (const candidate of candidates) {
      try {
        const content = fs.readFileSync(candidate, 'utf8')
        // Truncate large files to keep prompt manageable
        changedSources.push(`--- ${src} ---\n${content.slice(0, 3000)}`)
        break
      } catch {}
    }
  }

  if (changedSources.length === 0) {
    log('debug', 'No readable changed sources for doc', { doc: staleInfo.doc })
    return null
  }

  const oldVersion = staleInfo.version || '1.0.0'
  const newVersion = bumpPatch(oldVersion)
  const today = new Date().toISOString().slice(0, 10)

  const prompt = UPDATE_PROMPT
    .replace('{{current_doc}}', currentDoc.slice(0, 6000)) // Truncate very long docs
    .replace('{{changed_sources}}', changedSources.join('\n\n'))
    .replace('{{old_version}}', oldVersion)
    .replace('{{new_version}}', newVersion)
    .replace('{{today}}', today)

  try {
    // Use Kimi K2.5 via Moonshot API for doc generation (same as all daemon LLM calls)
    let updatedDoc = await callLLM(prompt, 4000)
    // Strip markdown code block wrappers if present
    updatedDoc = updatedDoc.replace(/^```(?:markdown|md)?\s*/m, '').replace(/\s*```\s*$/m, '').trim()

    if (updatedDoc.length < 100) throw new Error('Updated doc too short')

    // Validate: ensure the output looks like a markdown doc
    if (!updatedDoc.includes('#')) throw new Error('Updated doc has no headers')

    // Write back
    fs.writeFileSync(docPath, updatedDoc + '\n')

    // Record in manifest
    recordUpdate(stateDir, staleInfo.doc, newVersion)

    log('info', 'Doc auto-updated', {
      doc: staleInfo.doc,
      version: `${oldVersion} → ${newVersion}`,
      changedFiles: staleInfo.changedFiles.length
    })

    return { doc: staleInfo.doc, oldVersion, newVersion }
  } catch (err) {
    log('error', 'Doc auto-update failed', { doc: staleInfo.doc, error: err.message })
    return null
  }
}

/**
 * Git commit and push doc updates.
 * @param {string} projectRoot
 * @param {Object[]} updates - [{ doc, oldVersion, newVersion }]
 * @param {Function} log
 */
function commitAndPush(projectRoot, updates, log) {
  if (updates.length === 0) return

  const { execSync } = require('child_process')
  const opts = { cwd: projectRoot, timeout: 30000, stdio: ['pipe', 'pipe', 'pipe'] }

  try {
    // Stage only the updated doc files
    const files = updates.map(u => `docs/project/${u.doc}`)
    execSync(`git add ${files.join(' ')}`, opts)

    // Build commit message
    const changes = updates.map(u => `  - ${u.doc}: ${u.oldVersion} → ${u.newVersion}`).join('\n')
    const msg = `docs: auto-update ${updates.length} doc(s)\n\n${changes}\n\nAuto-generated by Quoth daemon doc-updater.`

    execSync(`git commit -m ${JSON.stringify(msg)}`, opts)
    execSync('git push', opts)

    log('info', 'Doc updates committed and pushed', { count: updates.length })
  } catch (err) {
    log('error', 'Git commit/push failed', { error: err.message })
  }
}

module.exports = { updateDoc, commitAndPush }
