'use strict'

/**
 * Doc Auto-Updater — reads a stale doc + changed source files, uses `claude -p`
 * (Sonnet 4.6) to generate an incremental update, bumps version, writes back.
 *
 * Execution log: ~/.quoth/intelligence/doc-update-log.jsonl
 * No LLM fallbacks — if claude CLI fails, the error is reported as-is.
 */

const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')
const { bumpPatch, VERSION_RE, recordUpdate } = require('./doc-manifest.js')

const LOG_FILE = 'doc-update-log.jsonl'

function appendExecLog(stateDir, entry) {
  try {
    const logPath = path.join(stateDir, LOG_FILE)
    fs.appendFileSync(logPath, JSON.stringify({ ...entry, ts: new Date().toISOString() }) + '\n')
  } catch {}
}

/**
 * Update a single stale doc using `claude -p` with Sonnet 4.6.
 * @param {string} projectRoot - Project root dir
 * @param {string} stateDir - ~/.quoth/intelligence/
 * @param {Object} staleInfo - { doc, version, changedFiles }
 * @param {Function} log - Logging function
 * @returns {Object|null} { doc, oldVersion, newVersion } or null on failure
 */
async function updateDoc(projectRoot, stateDir, staleInfo, log) {
  const docsDir = path.join(projectRoot, 'docs', 'project')
  const docPath = path.join(docsDir, staleInfo.doc)

  if (!fs.existsSync(docPath)) {
    const err = `Doc file not found: ${docPath}`
    appendExecLog(stateDir, { event: 'update_failed', doc: staleInfo.doc, error: err })
    log('error', err)
    return null
  }

  // Resolve source file paths so claude knows where to read them
  const resolvedFiles = []
  for (const src of staleInfo.changedFiles) {
    for (const candidate of [
      path.join(projectRoot, src),
      path.join(projectRoot, 'quoth-plugin', src),
      path.join(projectRoot, src.replace(/^quoth-plugin\//, '')),
    ]) {
      if (fs.existsSync(candidate)) { resolvedFiles.push(candidate); break }
    }
  }

  if (resolvedFiles.length === 0) {
    appendExecLog(stateDir, { event: 'update_skipped', doc: staleInfo.doc, reason: 'no source files found' })
    log('debug', 'No source files found', { doc: staleInfo.doc })
    return null
  }

  const oldVersion = staleInfo.version || '1.0.0'
  const newVersion = bumpPatch(oldVersion)
  const today = new Date().toISOString().slice(0, 10)

  const prompt = [
    `Update the documentation file: ${docPath}`,
    `These source files changed since the doc was last updated:`,
    resolvedFiles.map(f => `  - ${f}`).join('\n'),
    '',
    `Read the doc and each source file. Edit the doc to reflect the current source code.`,
    `Version: ${oldVersion} → ${newVersion}. Date: ${today}.`,
    `Make targeted edits only. Do not rewrite unchanged sections.`,
  ].join('\n')

  try {
    // Use claude CLI with Sonnet 4.6 and full tool access to edit directly
    execSync(
      'claude -p --model claude-sonnet-4-6 --dangerously-skip-permissions',
      {
        input: prompt,
        encoding: 'utf8',
        timeout: 600000, // 10 min per doc
        maxBuffer: 2 * 1024 * 1024,
        stdio: ['pipe', 'pipe', 'pipe'],
        cwd: projectRoot,
      }
    )

    // Verify the doc was actually modified
    const updatedContent = fs.readFileSync(docPath, 'utf8')
    if (!updatedContent.includes('#')) {
      throw new Error('Doc file has no markdown headers after edit')
    }

    // Record in manifest
    recordUpdate(stateDir, staleInfo.doc, newVersion, projectRoot)

    appendExecLog(stateDir, {
      event: 'update_success', doc: staleInfo.doc,
      oldVersion, newVersion,
      changedFiles: staleInfo.changedFiles,
    })

    log('info', 'Doc auto-updated', {
      doc: staleInfo.doc,
      version: `${oldVersion} → ${newVersion}`,
      changedFiles: staleInfo.changedFiles.length,
    })

    return { doc: staleInfo.doc, oldVersion, newVersion }
  } catch (err) {
    appendExecLog(stateDir, {
      event: 'update_failed', doc: staleInfo.doc, error: err.message,
      changedFiles: staleInfo.changedFiles,
      stderr: err.stderr ? err.stderr.toString().slice(0, 500) : undefined,
    })
    log('error', 'Doc auto-update failed', { doc: staleInfo.doc, error: err.message })
    return null
  }
}

/**
 * Git commit and push doc updates.
 * @param {string} projectRoot
 * @param {Object[]} updates - [{ doc, oldVersion, newVersion }]
 * @param {Function} log
 */
function commitAndPush(projectRoot, updates, log) {
  if (updates.length === 0) return

  const { execSync } = require('child_process')
  const opts = { cwd: projectRoot, timeout: 30000, stdio: ['pipe', 'pipe', 'pipe'] }

  try {
    // Stage only the updated doc files
    const files = updates.map(u => `docs/project/${u.doc}`)
    execSync(`git add ${files.join(' ')}`, opts)

    // Build commit message
    const changes = updates.map(u => `  - ${u.doc}: ${u.oldVersion} → ${u.newVersion}`).join('\n')
    const msg = `docs: auto-update ${updates.length} doc(s)\n\n${changes}\n\nAuto-generated by Quoth daemon doc-updater.`

    execSync(`git commit -m ${JSON.stringify(msg)}`, opts)
    execSync('git push', opts)

    log('info', 'Doc updates committed and pushed', { count: updates.length })
  } catch (err) {
    log('error', 'Git commit/push failed', { error: err.message })
  }
}

module.exports = { updateDoc, commitAndPush, appendExecLog }
