import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import childProcess from 'child_process'

beforeEach(() => {
  vi.spyOn(childProcess, 'execSync')
  vi.clearAllMocks()
})

afterEach(() => {
  vi.restoreAllMocks()
})

const { extract, makeId, QUALITY_MAP, QUALITY_PRIORS } = require('../daemon/pipeline/extract.js')

// Mock db with insertPipelineError and recordPipelineCost
function mockDb() {
  return {
    insertPipelineError: vi.fn(),
    recordPipelineCost: vi.fn(),
  }
}

const SUMMARY = {
  project: 'quoth',
  outcome: 'success',
  success_rate: 0.9,
  user_intents: ['refactor auth module'],
  task: 'Session: 15 tool calls (Bash:8, Edit:4, Read:3). 14 ok, 1 fail.',
  session: 'sess-123',
}

const TOOL_ENTRIES = [
  { tool: 'Read', task: 'Read auth.js', outcome: 'success', llm_reasoning: 'Need to understand current auth flow' },
  { tool: 'Edit', task: 'Edit auth.js', outcome: 'success', llm_reasoning: 'Refactoring to middleware pattern' },
  { tool: 'Bash', task: 'Run npm test', outcome: 'success', llm_reasoning: 'Verify changes pass tests' },
]

describe('extract', () => {
  describe('makeId', () => {
    it('generates stable SHA1-based ID from pattern text', () => {
      const id1 = makeId('When refactoring auth, read all middleware files first')
      const id2 = makeId('When refactoring auth, read all middleware files first')
      expect(id1).toBe(id2)
      expect(id1).toHaveLength(12)
      expect(id1).toMatch(/^[a-f0-9]+$/)
    })

    it('different text produces different ID', () => {
      const id1 = makeId('pattern A')
      const id2 = makeId('pattern B')
      expect(id1).not.toBe(id2)
    })
  })

  describe('QUALITY_MAP', () => {
    it('maps categorical labels to numeric scores', () => {
      expect(QUALITY_MAP.universal).toBe(0.9)
      expect(QUALITY_MAP.domain).toBe(0.7)
      expect(QUALITY_MAP.project).toBe(0.5)
      expect(QUALITY_MAP.edge_case).toBe(0.3)
    })
  })

  describe('QUALITY_PRIORS', () => {
    it('maps categorical labels to initial alpha/beta', () => {
      expect(QUALITY_PRIORS.universal).toEqual({ alpha: 3, beta: 1 })
      expect(QUALITY_PRIORS.domain).toEqual({ alpha: 2, beta: 1 })
      expect(QUALITY_PRIORS.project).toEqual({ alpha: 1, beta: 1 })
      expect(QUALITY_PRIORS.edge_case).toEqual({ alpha: 1, beta: 2 })
    })
  })

  describe('extract() — primary model (claude -p)', () => {
    it('happy path: productive session returns patterns', async () => {
      childProcess.execSync.mockReturnValue(JSON.stringify({
        session_type: 'productive',
        patterns: [
          {
            pattern: 'When refactoring across multiple files in a monorepo, read all target files in parallel before making batch edits to ensure consistency',
            tags: ['refactoring', 'workflow'],
            intention: 'Ensure consistent refactoring across files',
            quality_signal: 'domain',
          },
        ],
      }))

      const db = mockDb()
      const result = await extract(SUMMARY, TOOL_ENTRIES, db)

      expect(result).toHaveLength(1)
      expect(result[0].pattern).toContain('refactoring across multiple files')
      expect(result[0].tags).toContain('refactoring')
      expect(result[0].intention).toBe('Ensure consistent refactoring across files')
      expect(result[0].quality_signal).toBe('domain')
      expect(result[0].id).toHaveLength(12)
      expect(result[0].source).toBe('distilled')
      // Embedding is generated by MiniLM-L6 (384d) if available, null otherwise
      if (result[0].embedding) {
        expect(result[0].embedding).toHaveLength(384)
      }
    })

    it('routine session returns empty array', async () => {
      childProcess.execSync.mockReturnValue(JSON.stringify({
        session_type: 'routine',
        patterns: [],
      }))

      const result = await extract(SUMMARY, TOOL_ENTRIES, mockDb())
      expect(result).toHaveLength(0)
    })

    it('returns 0 patterns when LLM says none are genuinely reusable', async () => {
      childProcess.execSync.mockReturnValue(JSON.stringify({
        session_type: 'productive',
        patterns: [],
      }))

      const result = await extract(SUMMARY, TOOL_ENTRIES, mockDb())
      expect(result).toHaveLength(0)
    })

    it('filters out patterns shorter than 20 chars', async () => {
      childProcess.execSync.mockReturnValue(JSON.stringify({
        session_type: 'productive',
        patterns: [
          { pattern: 'Too short', tags: [], intention: '', quality_signal: 'project' },
          {
            pattern: 'When debugging intermittent test failures, isolate the failing test first with .only then add verbose logging',
            tags: ['debugging'],
            intention: 'Fix flaky test',
            quality_signal: 'universal',
          },
        ],
      }))

      const result = await extract(SUMMARY, TOOL_ENTRIES, mockDb())
      expect(result).toHaveLength(1)
      expect(result[0].quality_signal).toBe('universal')
    })

    it('normalizes invalid quality_signal to "project"', async () => {
      childProcess.execSync.mockReturnValue(JSON.stringify({
        session_type: 'productive',
        patterns: [
          {
            pattern: 'Pattern with invalid quality signal that should be normalized to project default',
            tags: [],
            intention: '',
            quality_signal: 'legendary',
          },
        ],
      }))

      const result = await extract(SUMMARY, TOOL_ENTRIES, mockDb())
      expect(result).toHaveLength(1)
      expect(result[0].quality_signal).toBe('project')
    })

    it('caps tags at 5 per pattern', async () => {
      childProcess.execSync.mockReturnValue(JSON.stringify({
        session_type: 'productive',
        patterns: [
          {
            pattern: 'A pattern with way too many tags for any reasonable extraction scenario to produce',
            tags: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
            intention: '',
            quality_signal: 'project',
          },
        ],
      }))

      const result = await extract(SUMMARY, TOOL_ENTRIES, mockDb())
      expect(result[0].tags).toHaveLength(5)
    })
  })

  describe('extract() — primary failure + fallback', () => {
    it('logs primary error to pipeline_errors when claude -p fails', async () => {
      childProcess.execSync.mockImplementation(() => { throw new Error('claude not found') })

      const db = mockDb()
      // Fallback also fails (no API key in test env)
      const result = await extract(SUMMARY, TOOL_ENTRIES, db)

      // Primary error logged
      expect(db.insertPipelineError).toHaveBeenCalledWith(
        expect.objectContaining({
          stage: 'extract',
          error_message: expect.stringContaining('claude not found'),
          model_attempted: 'claude-sonnet-4-6',
          fallback_attempted: 1,
        })
      )
      // Both failed → empty result
      expect(result).toHaveLength(0)
    })
  })

  describe('extract() — JSON parse failure', () => {
    it('logs parse error and returns empty on invalid JSON', async () => {
      childProcess.execSync.mockReturnValue('This is not JSON at all, just random text')

      const db = mockDb()
      const result = await extract(SUMMARY, TOOL_ENTRIES, db)

      expect(result).toHaveLength(0)
      expect(db.insertPipelineError).toHaveBeenCalledWith(
        expect.objectContaining({
          stage: 'extract',
          error_message: expect.stringContaining('parse'),
        })
      )
    })
  })

  describe('extract() — multiple patterns', () => {
    it('returns all valid patterns from a productive session', async () => {
      childProcess.execSync.mockReturnValue(JSON.stringify({
        session_type: 'productive',
        patterns: [
          {
            pattern: 'When refactoring auth middleware, read all route handlers first to understand the dependency chain before making changes',
            tags: ['refactoring', 'architecture'],
            intention: 'Safe middleware refactoring',
            quality_signal: 'domain',
          },
          {
            pattern: 'For debugging intermittent test failures, isolate the failing test first with .only, then add verbose logging to setup and teardown hooks',
            tags: ['debugging', 'testing'],
            intention: 'Diagnose flaky tests',
            quality_signal: 'universal',
          },
        ],
      }))

      const result = await extract(SUMMARY, TOOL_ENTRIES, mockDb())
      expect(result).toHaveLength(2)
      expect(result[0].quality_signal).toBe('domain')
      expect(result[1].quality_signal).toBe('universal')
      // Each has a unique ID
      expect(result[0].id).not.toBe(result[1].id)
    })
  })
})
